### ISSUE TITLE
买不了卡

### ISSUE THREAD

**Issue by wjn3137823020** [hdward9/GoYoung#7]
买密钥的网址寄了

**Comment by heiwa9** [comment]
加我微信

**Comment by wjn3137823020** [comment]
> 加我微信

给个联系方式

**Comment by heiwa9** [comment]
dev_cheung  微信
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2024年05月22日 23:55:00
***@***.***>
抄　送：JOHNNY ***@***.***>; ***@***.***>
主　题：Re: [heiwa9/GoYoung] 买不了卡 (Issue #7)


加我微信 
给个联系方式
